name: Build container

on: workflow_dispatch

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker
        file: docker/Dockerfile.x86_64-unknown-freebsd
        push: true
        tags: ghcr.io/tesaguri/cross-freebsd-diesel_migrations-test/cross:x86_64-unknown-freebsd
