name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - modified
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-freebsd
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - name: Setup `Cross.toml`
        run: mv Cross.${{ matrix.config }}.toml Cross.toml
      - name: Install `cross`
        if: matrix.use_cross
        uses: actions-rs/install@v0.1
        with:
          crate: cross
          use-tool-cache: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --lib --target x86_64-unknown-freebsd
          use-cross: true
